# vmagent Configuration with proper scraping for kube-state-metrics

# Remote write URLs - this is the critical required field
remoteWrite:
  - url: http://victoria-metrics-victoria-metrics-cluster-vminsert.pod-metrics-dashboard.svc.cluster.local:8480/insert/0/prometheus/

# Enable RBAC for service discovery
rbac:
  create: true

# Service account
serviceAccount:
  create: true

# Scrape configurations to collect metrics from Kubernetes
config:
  global:
    scrape_interval: 30s
    external_labels:
      cluster: 'kubernetes'
      environment: 'pod-metrics-dashboard'
  
  scrape_configs:
    # Scrape kube-state-metrics for resource requests/limits
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: 
          - 'kube-state-metrics.pod-metrics-dashboard.svc.cluster.local:8080'
      scrape_interval: 30s
      honor_timestamps: true
      
    # Scrape kubelet cadvisor for container metrics (usage)
    - job_name: 'kubernetes-cadvisor'
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      metric_relabel_configs:
        - source_labels: [container]
          regex: POD
          action: drop
        - source_labels: [container]
          regex: ""
          action: drop

    # Scrape kubelet for node metrics
    - job_name: 'kubernetes-nodes'
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics

    # Scrape service endpoints that have prometheus.io/scrape=true annotation
    - job_name: 'kubernetes-service-endpoints'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name

# Resources for vmagent
resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 500Mi
    cpu: 500m
